# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'SignalR-ObjC'

source 'https://github.com/CocoaPods/Specs.git'

target 'Hangout' do

end

target 'HangoutTests' do

end

